name: Tests

on:
  pull_request: ~
  push: ~
  schedule:
    - cron: '0 9 * * 5'

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    services:
      db:
        image: mysql:8
        env:
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASS }}
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
        experimental: [false]
      fail-fast: false
    name: PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }}
    env:
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASS: test_password
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          tools: 'composer:v2'
          ini-values: error_reporting=E_ALL
          extensions: mbstring

      - name: Install dependencies
        run: composer update --ignore-platform-req=php --prefer-dist --no-progress --no-suggest

      - name: Start MySQL
        run: |
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USER }} -p${{ env.DB_PASS }}  

      - name: Run test.sql
        run: mysql --protocol=tcp -h localhost --port 33306 -u${{ env.DB_USER }} -p${{ env.DB_PASS }} < tests/data/test.sql

      - name: Run the tests
        run: composer run tests

